defaults:
    - machine: cluster
    - paths: default
    - model: resnet18_cifar
    - optim: adamw
    - lrsched: timm_cosine
    - /transform@train_transforms: train_transform
    - /transform@eval_transforms: eval_transform
    - _self_


hydra:
    run:
        dir: ${paths.run_dir}
    job_logging:
        formatters:
            simple:
                format: "%(asctime)s - %(message)s"
                datefmt: "%Y-%m-%d %H:%M:%S"

data:
    name: cifar10
    num_workers: 4
    download: true
    data_split_seed: 1
    train_val_split_factor: 0.1

proj_dir_name: deconcnn
run_name: base

load_checkpoint:
enable_checkpointing: False
log_every: 1
limit_train_batches:

seed: 0
train: true
eval: false

epochs: 50
batch_size: 128
loss: cross_entropy
clip_grad_norm:
