_target_: "dr_exp.trainers.decon_trainer.train_decon"
defaults:
    - machine: cluster
    - paths: default
    - model: resnet18_cifar
    - optim: adamw
    - lrsched: timm_cosine
    - /transform@train_transforms: train_transform
    - /transform@eval_transforms: eval_transform
    - _self_


hydra:
    run:
        dir: ${paths.run_dir}
    job_logging:
        formatters:
            simple:
                format: "%(asctime)s - %(message)s"
                datefmt: "%Y-%m-%d %H:%M:%S"

data:
    name: cifar10
    num_workers: 4
    download: true
    data_split_seed: 1
    train_val_split_factor: 0.1

proj_dir_name: deconcnn

limit_train_batches:
load_checkpoint:
enable_checkpointing: False
log_every: 1

seed: 0
train: true
eval: false

epochs: 1
batch_size: 10
loss: cross_entropy
clip_grad_norm:
