#!/usr/bin/env python3
"""Deploy schema to remote Supabase instance."""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    print("Error: SUPABASE_URL and SUPABASE_KEY must be set in .env")
    sys.exit(1)

# Extract database connection details from URL
# Format: https://PROJECT_REF.supabase.co
project_ref = SUPABASE_URL.split("//")[1].split(".")[0]
db_host = f"db.{project_ref}.supabase.co"
db_name = "postgres"
db_user = "postgres"
db_password = SUPABASE_KEY  # For direct connection, we need the database password

print(f"🚀 Deploying to remote Supabase project: {project_ref}")
print(f"   Database host: {db_host}")

# For now, let's use the REST API to check connection
import requests

headers = {"apikey": SUPABASE_KEY, "Authorization": f"Bearer {SUPABASE_KEY}"}

# Test connection
response = requests.get(f"{SUPABASE_URL}/rest/v1/", headers=headers)
if response.status_code == 200:
    print("✅ Connection to Supabase verified")
else:
    print(f"❌ Failed to connect: {response.status_code}")
    sys.exit(1)

# Since we can't directly connect to the DB without the postgres password,
# we'll create a SQL script to run via Supabase dashboard
migrations_dir = Path("supabase/migrations")
combined_sql = Path("deploy_combined.sql")

print("\n📝 Creating combined migration script...")

with open(combined_sql, "w") as output:
    output.write("-- Combined migration script for remote deployment\n")
    output.write("-- Generated by deploy_to_remote.py\n\n")

    # First, add cleanup commands
    output.write("-- Step 1: Clean up existing schema\n")
    output.write("DROP VIEW IF EXISTS job_queue CASCADE;\n")
    output.write("DROP VIEW IF EXISTS experiment_stats CASCADE;\n")
    output.write("DROP TABLE IF EXISTS sync_status CASCADE;\n")
    output.write("DROP TABLE IF EXISTS jobs CASCADE;\n")
    output.write("DROP TABLE IF EXISTS experiments CASCADE;\n\n")

    # Then add all migrations
    sql_files = sorted(migrations_dir.glob("*.sql"))
    for i, sql_file in enumerate(sql_files, 1):
        if sql_file.name == "README.md":
            continue

        output.write(f"-- Step {i + 1}: {sql_file.name}\n")
        output.write(sql_file.read_text())
        output.write("\n\n")

print(f"✅ Combined SQL script created: {combined_sql}")
print("\n📋 Next steps:")
print(
    "1. Go to your Supabase Dashboard: https://supabase.com/dashboard/project/"
    + project_ref
)
print("2. Navigate to SQL Editor")
print("3. Copy and paste the contents of 'deploy_combined.sql'")
print("4. Click 'Run' to execute the migration")
print("\nAlternatively, if you have the database password, you can set it as:")
print("export PGPASSWORD='your-database-password'")
print(
    "Then run: psql -h " + db_host + " -U postgres -d postgres -f deploy_combined.sql"
)
